// <auto-generated />
using System;
using Application.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(FlowerShopManagerDbContext))]
    [Migration("20260606225702_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("Application.Domain.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecieverId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecieverId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 1, 10, 6, 0, 0, DateTimeKind.Unspecified),
                            IsSeen = true,
                            Message = "Your order #1 has been completed!",
                            RecieverId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 3, 14, 36, 0, 0, DateTimeKind.Unspecified),
                            IsSeen = false,
                            Message = "Your order #2 is currently being processed.",
                            RecieverId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 10, 9, 21, 0, 0, DateTimeKind.Unspecified),
                            IsSeen = false,
                            Message = "Your order #3 has been received.",
                            RecieverId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSeen = true,
                            Message = "Low stock alert: Orchid Plant has 20 units.",
                            RecieverId = 2
                        });
                });

            modelBuilder.Entity("Application.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 3,
                            OrderDate = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalAmount = 49.979999999999997
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 4,
                            OrderDate = new DateTime(2024, 4, 3, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalAmount = 34.990000000000002
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2024, 4, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalAmount = 12.49
                        });
                });

            modelBuilder.Entity("Application.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 29.989999999999998
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 19.989999999999998
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 34.990000000000002
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 12.49
                        });
                });

            modelBuilder.Entity("Application.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 49.979999999999997,
                            Date = new DateTime(2024, 4, 1, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 34.990000000000002,
                            Date = new DateTime(2024, 4, 3, 14, 35, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 12.49,
                            Date = new DateTime(2024, 4, 10, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Application.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic bouquet of 12 fresh red roses.",
                            Name = "Red Roses Bouquet",
                            Price = 29.989999999999998,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bright arrangement of 6 sunflowers.",
                            Name = "Sunflower Arrangement",
                            Price = 19.989999999999998,
                            Stock = 40
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dried lavender bundle, great for home decor.",
                            Name = "Lavender Bundle",
                            Price = 12.49,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Description = "Seasonal mix of tulips, daisies and peonies.",
                            Name = "Mixed Spring Bouquet",
                            Price = 34.990000000000002,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            Description = "Potted white orchid, long-lasting gift.",
                            Name = "Orchid Plant",
                            Price = 44.990000000000002,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("Application.Domain.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneratedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedById");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Total sales in April: $97.46 across 3 orders.",
                            CreatedAt = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneratedById = 1,
                            Title = "April Sales Summary"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Orchid Plant stock is below 25 units. Reorder advised.",
                            CreatedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneratedById = 2,
                            Title = "Low Stock Alert Report"
                        });
                });

            modelBuilder.Entity("Application.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice@flowerShop.com",
                            FirstName = "Alice",
                            LastName = "Admin",
                            Password = "hashed_pw_1",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob@flowerShop.com",
                            FirstName = "Bob",
                            LastName = "Staff",
                            Password = "hashed_pw_2",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carol@example.com",
                            FirstName = "Carol",
                            LastName = "Customer",
                            Password = "hashed_pw_3",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david@example.com",
                            FirstName = "David",
                            LastName = "Customer",
                            Password = "hashed_pw_4",
                            Role = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "123",
                            FirstName = "David",
                            LastName = "Customer",
                            Password = "123",
                            Role = 0
                        });
                });

            modelBuilder.Entity("Application.Domain.Notification", b =>
                {
                    b.HasOne("Application.Domain.User", "Reciever")
                        .WithMany()
                        .HasForeignKey("RecieverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reciever");
                });

            modelBuilder.Entity("Application.Domain.Order", b =>
                {
                    b.HasOne("Application.Domain.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Application.Domain.OrderItem", b =>
                {
                    b.HasOne("Application.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Application.Domain.Payment", b =>
                {
                    b.HasOne("Application.Domain.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Application.Domain.Report", b =>
                {
                    b.HasOne("Application.Domain.User", "GeneratedBy")
                        .WithMany()
                        .HasForeignKey("GeneratedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedBy");
                });

            modelBuilder.Entity("Application.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
