using Application.Domain;
using Application.Service;
using Application.Service.Interfaces;
using System.Data;

namespace UI
{
    public partial class ReportForm : Form
    {
        private readonly User _user;
        private readonly IReportService _reportService;
        private readonly IPaymentService _paymentService;
        private readonly IOrderService _orderService;
        private readonly IProductService _productService;
        private List<Report> _reports = new();

        public ReportForm(User user)
        {
            InitializeComponent();
            _user = user;
            _reportService = new ReportService();
            _paymentService = new PaymentService();
            _orderService = new OrderService();
            _productService = new ProductService();
        }

        private void ReportForm_Load(object sender, EventArgs e)
        {
            LoadReports();
        }

        private void LoadReports()
        {
            try
            {
                _reports = _reportService.GetAll().OrderByDescending(r => r.CreatedAt).ToList();
                var dt = new DataTable();
                dt.Columns.Add("Id", typeof(int));
                dt.Columns.Add("Title", typeof(string));
                dt.Columns.Add("Generated By", typeof(string));
                dt.Columns.Add("Date", typeof(DateTime));

                foreach (var r in _reports)
                    dt.Rows.Add(r.Id, r.Title, $"{r.GeneratedBy.FirstName} {r.GeneratedBy.LastName}", r.CreatedAt);

                dataGridView1.DataSource = dt;
                dataGridView1.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
                dataGridView1.RowHeadersVisible = false;
                dataGridView1.AllowUserToAddRows = false;

                // Add details button column if not already present
                if (!dataGridView1.Columns.Contains("DetailsCol"))
                {
                    var btn = new DataGridViewButtonColumn();
                    btn.HeaderText = "Details";
                    btn.Text = "View";
                    btn.UseColumnTextForButtonValue = true;
                    btn.Name = "DetailsCol";
                    dataGridView1.Columns.Add(btn);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Greška", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            if (dataGridView1.Columns[e.ColumnIndex].Name == "DetailsCol")
            {
                int id = Convert.ToInt32(dataGridView1.Rows[e.RowIndex].Cells["Id"].Value);
                var report = _reports.FirstOrDefault(r => r.Id == id);
                if (report != null)
                    MessageBox.Show(report.Content, report.Title, MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void GenerateSalesButton_Click(object sender, EventArgs e)
        {
            try
            {
                DateTime from = FromdateTimePicker1.Value.Date;
                DateTime to = TodateTimePicker2.Value.Date.AddDays(1).AddSeconds(-1);
                if (from > to)
                    throw new Exception("Start date must be before end date.");

                var payments = _paymentService.GetAll()
                    .Where(p => p.Status == PaymentStatus.Completed && p.Date >= from && p.Date <= to)
                    .ToList();
                var orders = _orderService.GetAll()
                    .Where(o => o.OrderDate >= from && o.OrderDate <= to)
                    .ToList();

                double revenue = payments.Sum(p => p.Amount);
                int totalOrders = orders.Count;
                var statusCounts = orders.GroupBy(o => o.Status)
                    .Select(g => $"{g.Key}: {g.Count()}").ToList();

                string title = $"Sales Report {from:yyyy-MM-dd} to {TodateTimePicker2.Value.Date:yyyy-MM-dd}";
                string content = $"Period: {from:yyyy-MM-dd} to {TodateTimePicker2.Value.Date:yyyy-MM-dd}\n" +
                                 $"Total Revenue: ${revenue:F2}\n" +
                                 $"Total Orders: {totalOrders}\n" +
                                 $"Orders by Status:\n  {string.Join("\n  ", statusCounts)}";

                var report = new Report(_user, title, content, DateTime.Now);
                _reportService.Create(report);
                LoadReports();
                MessageBox.Show("Sales report generated successfully.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Greška", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void GenerateLowStockButton_Click(object sender, EventArgs e)
        {
            try
            {
                var lowStock = _productService.GetLowStock(25);
                string title = $"Low Stock Report {DateTime.Now:yyyy-MM-dd}";
                string content = $"Low Stock Products (threshold: 25)\n\n" +
                    string.Join("\n", lowStock.Select(p => $"- {p.Name}: {p.Stock} in stock (Price: ${p.Price:F2})"));

                var report = new Report(_user, title, content, DateTime.Now);
                _reportService.Create(report);
                LoadReports();
                MessageBox.Show("Low stock report generated successfully.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Greška", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
    }
}
